/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BrandSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = BrandSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = CategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaintenanceSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'date', 'id', 'maintenanceRequestId', 'maintenanceStatusId', 'technicianId', 'typeId', 'updatedAt', 'vehicleId'] as const
  $columns = MaintenanceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column.dateTime()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maintenanceRequestId: number
  @column()
  declare maintenanceStatusId: number
  @column()
  declare technicianId: number
  @column()
  declare typeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vehicleId: number
}

export class MaintenanceRequestSchema extends BaseModel {
  static $columns = ['approvedDate', 'createdAt', 'customerId', 'id', 'requestDate', 'technicianId', 'typeId', 'updatedAt', 'vehicleId'] as const
  $columns = MaintenanceRequestSchema.$columns
  @column.dateTime()
  declare approvedDate: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare requestDate: DateTime
  @column()
  declare technicianId: number
  @column()
  declare typeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vehicleId: number
}

export class MaintenanceServiceTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'duration', 'id', 'name', 'price', 'updatedAt'] as const
  $columns = MaintenanceServiceTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare duration: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare price: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaintenanceStatusSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = MaintenanceStatusSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ModelSchema extends BaseModel {
  static $columns = ['brandId', 'categoryId', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = ModelSchema.$columns
  @column()
  declare brandId: number | null
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RentalSchema extends BaseModel {
  static $columns = ['createdAt', 'endDate', 'id', 'startDate', 'totalPrice', 'updatedAt', 'userId', 'vehicleId'] as const
  $columns = RentalSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare totalPrice: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
  @column()
  declare vehicleId: number
}

export class TicketSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'description', 'id', 'statusId', 'technicianId', 'title', 'updatedAt'] as const
  $columns = TicketSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare statusId: number
  @column()
  declare technicianId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketCommentSchema extends BaseModel {
  static $columns = ['authorId', 'comment', 'createdAt', 'id', 'ticketId', 'updatedAt'] as const
  $columns = TicketCommentSchema.$columns
  @column()
  declare authorId: number
  @column()
  declare comment: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ticketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TicketStatusSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = TicketStatusSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstname', 'id', 'lastname', 'password', 'phoneNumber', 'roles', 'type', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstname: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastname: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare roles: any
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VehicleSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'dailyPrice', 'id', 'mileage', 'modelId', 'price', 'registration', 'type', 'updatedAt', 'year'] as const
  $columns = VehicleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column()
  declare dailyPrice: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mileage: string
  @column()
  declare modelId: number | null
  @column()
  declare price: string | null
  @column()
  declare registration: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare year: number
}
