/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  SalableVehicles: () => import('#controllers/salable_vehicles_controller'),
  Brands: () => import('#controllers/brands_controller'),
}
